#! /usr/bin/env python3

import time
import rospy
from std_msgs.msg import String, UInt8, UInt8MultiArray, Float32, Float32MultiArray
from sensor_msgs.msg import JointState
from open_manipulator_msgs.srv import *

from open_manipulator_haptic_bridge.thread_wrapper import periodic

class OpenManipulatorBridgeNode:

    def __init__(self):
        self.angles = [0.0, 0.0, 0.0, 0.0]
        self.buttons = [0, 0, 0, 0, 0, 0]
        self.feedback = 0
        self.feedbackPattern = 0
        self.feedback_to_send = UInt8()
        self.lastJointSentTime = 0
        self.lastGripperSentTime = 0
        self.lastActuatorSentTime = 0
        self.gripperValue = 0.0
        self.lastGripperValue = 0.0
        self.grippingCounter = 0
        self.sendTactileFeedback = True
                    
    def main(self):                      
        self.feedbackPub  = rospy.Publisher('/mogi_haptic/feedback_request', UInt8, queue_size=1)
                                        
        rospy.init_node('open_manipulator_bridge')
        self.nodeName = rospy.get_name()
        rospy.loginfo("{0} started".format(self.nodeName))

        self.set_actuator_state(False)

        self.publishRate = float(rospy.get_param('~publish_rate', 50.0)) # in Hz
        self.serviceRate = float(rospy.get_param('~service_rate', 100.0)) # in Hz

        rospy.Subscriber("/mogi_haptic/joint_angles", Float32MultiArray, self.jointCallback)
        rospy.Subscriber("/mogi_haptic/button_states", UInt8MultiArray, self.buttonCallback)
        rospy.Subscriber("/open_manipulator/joint_states", JointState, self.deviceJointCallback)

        self.periodicThread = periodic(self.feedbackThread, 0.01, "Feedback")
        self.periodicThread.start()

        rate = rospy.Rate(self.publishRate)
        while not rospy.is_shutdown():
            self.publish()
            try:
                rate.sleep()
            except:
                print("Ctrl+C occured")

        
        print("Stopped")

        self.periodicThread.exit()

    def publish(self):
        self.feedback_to_send.data = self.feedback
        self.feedbackPub.publish(self.feedback_to_send)


    def jointCallback(self, data):
        self.angles = list(data.data)
        #print(self.angles)
        if time.time() > self.lastJointSentTime + 1.0/self.serviceRate:
            self.set_joint_client(self.angles[0],self.angles[1],self.angles[2],self.angles[3],1.0/self.serviceRate)
            self.lastJointSentTime = time.time()

    def buttonCallback(self, data):
        self.buttons = list(data.data)
        #print(self.buttons)
        if self.buttons[1] == 1:
            self.gripperValue = 0.01
            self.feedbackPattern = 1
        elif self.buttons[0] == 1:
            self.gripperValue = -0.01
            self.feedbackPattern = 2

        if self.buttons[3] == 1:
            self.set_actuator_state(False)
        elif self.buttons[2] == 1:
            self.set_actuator_state(True)

        if time.time() > self.lastGripperSentTime + 1.0/self.serviceRate:
            if self.lastGripperValue != self.gripperValue:
                self.set_gripper_client(self.gripperValue,1)
                self.lastGripperValue = self.gripperValue
            

    def deviceJointCallback(self, data):
        #print(list(data.position))
        
        if self.gripperValue == -0.01:
            if abs(self.gripperValue - data.position[4]) > 0.0001:
                self.grippingCounter += 1
                if self.grippingCounter > 120 and self.sendTactileFeedback:
                    print(abs(self.gripperValue - data.position[4]))
                    self.sendTactileFeedback = False
                    self.feedbackPattern = 3
            else:
                self.grippingCounter = 0
        else:
            self.grippingCounter = 0
            self.sendTactileFeedback = True

    def set_joint_client(self, j1, j2, j3, j4, time):
        service_name = '/open_manipulator/goal_joint_space_path'

        rospy.wait_for_service(service_name,1)
        try:
            set_joint_angles = rospy.ServiceProxy(service_name, SetJointPosition)
            arg = SetJointPositionRequest()
            arg.joint_position.joint_name = ["joint1", "joint2", "joint3", "joint4"]
            arg.joint_position.position = [j1, j2, j3, j4]
            arg.path_time = time
            resp1 = set_joint_angles(arg)
            print('Service done!')
            return resp1
        except rospy.ServiceException as e:
            print("Service call failed: %s"%e)
            return False

    def set_gripper_client(self, gripper, time):
        service_name = '/open_manipulator/goal_tool_control'

        rospy.wait_for_service(service_name,1)

        try:
            set_joint_angles = rospy.ServiceProxy(service_name, SetJointPosition)

            arg = SetJointPositionRequest()
            arg.joint_position.joint_name = ["gripper"]
            arg.joint_position.position = [gripper]
            arg.path_time = time
            resp1 = set_joint_angles(arg)
            print('Service done!')
            return resp1
        except rospy.ServiceException as e:
            print("Service call failed: %s"%e)
            return False

    def set_actuator_state(self, state):
        service_name = '/open_manipulator/set_actuator_state'

        rospy.wait_for_service(service_name,1)

        try:
            set_state = rospy.ServiceProxy(service_name, SetActuatorState)

            arg = SetActuatorStateRequest()
            arg.set_actuator_state = state
            resp1 = set_state(arg)
            print('Service done!')
            return resp1
        except rospy.ServiceException as e:
            print("Service call failed: %s"%e)
            return False

    def feedbackThread(self):

        try:
            if self.feedbackPattern == 1: #OPEN
                self.feedback = 30
                time.sleep(0.07)
                self.feedback = 0
                time.sleep(0.07)
                self.feedback = 30
                time.sleep(0.07)
                self.feedback = 0
                time.sleep(0.2)
                self.feedbackPattern = 0
            elif self.feedbackPattern == 2: #CLOSE
                self.feedback = 30
                time.sleep(0.1)
                self.feedback = 0
                time.sleep(0.4)
                self.feedbackPattern = 0
            elif self.feedbackPattern == 3: #GRABBING
                self.feedback = 40
                time.sleep(0.3)
                self.feedback = 0
                time.sleep(0.2)
                self.feedbackPattern = 0
            else:
                self.feedback = 0
                self.feedbackPattern = 0
        except:
            print("exception")
            time.sleep(2.0)


if __name__ == '__main__':
    try:
        node = OpenManipulatorBridgeNode()
        node.main()
    except rospy.ROSInterruptException:
        pass



    
    
